language: haskell
ghc: 7.8.3

script:
  - cabal configure --enable-tests --enable-library-coverage && cabal build
  - run-cabal-test --show-details=always

after_script:
  - hpc-coveralls test doctests --exclude-dir={test,dist}

