language: haskell

before_install:
  - cabal install hpc-coveralls -j --bindir=$HOME/.cabal/bin/

script:
  - cabal configure --enable-tests --enable-library-coverage --ghc-options=-Werror && cabal build
  - run-cabal-test --show-details=always

after_script:
  - hpc-coveralls Tests --exclude-dir=Tests

