language: haskell
ghc: 7.8
sudo: required

before_install:
    - sudo apt-get -q -y install hlint || cabal install hlint

script:
  - hlint src test --ignore="Parse error"
  - cabal configure --enable-tests --enable-library-coverage && cabal build
  - cabal test --show-details=always

cache:
  directories:
  - ~/.cabal
  - ~/.ghc

after_script:
  - cabal install hpc-coveralls
  - hpc-coveralls test doctests --exclude-dir={test,dist}

