language: haskell
ghc: 7.6

script:
  - cabal configure --enable-tests --enable-library-coverage && cabal build && cabal test

cache:
  directories:
  - ~/.cabal
  - ~/.ghc

after_script:
  - cabal install hpc-coveralls
  - hpc-coveralls test doctests --exclude-dir={test,dist}

