language: haskell

script:
  - cabal configure --enable-tests --enable-library-coverage && cabal build && cabal test

after_script:
  - cabal install hpc-coveralls -j --bindir=$HOME/.cabal/bin/
  - hpc-coveralls spec --exclude-dir=Tests

